apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: music-app
spec:
  selector:
    app: music-frontend
  ports:
    - port: 80
      targetPort: 80
  #type: NodePort # user nodeport to access the frontend service from outside the cluster
  type: ClusterIP # use clusterip to access the frontend service from the ingress controller