apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  username: {{ .Values.mysql.secret.username | quote }}
  password: {{ .Values.mysql.secret.password | quote }}
  root-password: {{ .Values.mysql.secret.rootPassword | quote }}